services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mapleplan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mapleplan_db
    volumes:
      - mapleplan_db_data:/var/lib/postgresql

volumes:
  mapleplan_db_data:
    external: true